# Generated by Django 5.1.3 on 2024-11-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_story', models.TextField()),
                ('pe', models.TextField()),
                ('dd', models.TextField()),
                ('complementary_investigations', models.TextField()),
                ('best_diagnostic_test', models.TextField()),
                ('treatment', models.TextField()),
            ],
        ),
    ]
