# Generated by Django 5.1.3 on 2024-11-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
