# Generated by Django 5.1.3 on 2024-11-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_folder_alter_disease_name_disease_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='diseases.folder'),
        ),
    ]
